module.exports = {
	"zh-CN": {
		scheduler_role_nickname: "调度员",
	},
	"en-US": {
		scheduler_role_nickname: "Scheduler",
	},
	MESSAGE_TYPE: {
		TEXT: "text",
		EMOJI: "emoji",
		IMAGE: "image",
		FILE: "file",
		MENU: "menu",
		ARTICLE: "article",
		EVALUATE_REQUEST: "evaluateRequest",
		WAIT_TIMEOUT: "waitTimeout",
		TEXT_EXT: "textExt",
	},
	FEATURE: {
		CREATE_TICKET: "createTicket",
		EVALUATE_AGENT: "evaluateAgent",
		CALL_ROBOT_MENU: "callRobotMenu",
		TRANSFER_TO_MANUAL: "transferToManual",
		CLOSE_SESSION: "closeSession",
	},
	COMMAND_MESSAGE: {
		SESSION_CREATED: "sessionCreated",
		SESSION_OPENED: "sessionOpened",
		SESSION_TRANSFERED: "sessionTransfered",
		SESSION_TRANSFERING: "sessionTransfering",
		SESSION_CLOSED: "sessionClosed",
		MESSAGE_RECALLED: "messageRecalled",
	},

  // 表情包图片路径，请根据实际情形修改
  EMOJI_PATH: "../../images/faces/",
  EMOJI_MAP: {
    "[):]": "ee_1.png",
    "[:D]": "ee_2.png",
    "[;)]": "ee_3.png",
    "[:-o]": "ee_4.png",
    "[:p]": "ee_5.png",
    "[(H)]": "ee_6.png",
    "[:@]": "ee_7.png",
    "[:s]": "ee_8.png",
    "[:$]": "ee_9.png",
    "[:(]": "ee_10.png",
    "[:'(]": "ee_11.png",
    "[:|]": "ee_12.png",
    "[(a)]": "ee_13.png",
    "[8o|]": "ee_14.png",
    "[8-|]": "ee_15.png",
    "[+o(]": "ee_16.png",
    "[<o)]": "ee_17.png",
    "[|-)]": "ee_18.png",
    "[*-)]": "ee_19.png",
    "[:-#]": "ee_20.png",
    "[:-*]": "ee_21.png",
    "[^o)]": "ee_22.png",
    "[8-)]": "ee_23.png",
    "[(|)]": "ee_24.png",
    "[(u)]": "ee_25.png",
    "[(S)]": "ee_26.png",
    "[(*)]": "ee_27.png",
    "[(#)]": "ee_28.png",
    "[(R)]": "ee_29.png",
    "[({)]": "ee_30.png",
    "[(})]": "ee_31.png",
    "[(k)]": "ee_32.png",
    "[(F)]": "ee_33.png",
    "[(W)]": "ee_34.png",
    "[(D)]": "ee_35.png"
  },
};

